### ISSUE TITLE
java.net.ConnectException Failed to connect to (Host) connect failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by firasalmanna** [cloudant/sync-android#526] opened 2017-04-13 16:25 UTC
Hello,

I am getting this error in my Crashlytics dashboard a lot, and some users reported that the app is not working (which means the sync is not working).   

```
#0. Crashed: Replicator: PullStrategy - https://user.cloudant.com:443/topics: 0 0 0x0000000000000000
       at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:144)
       at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:89)
       at com.cloudant.mazha.CouchClient.execute(CouchClient.java:193)
       at com.cloudant.mazha.CouchClient.isBulkSupported(CouchClient.java:749)
       at com.cloudant.sync.replication.CouchClientWrapper.isBulkSupported(CouchClientWrapper.java:280)
       at com.cloudant.sync.replication.PullStrategy.run(PullStrategy.java:176)
       at java.lang.Thread.run(Thread.java:762)

--

Non-fatal Exception: com.cloudant.mazha.CouchException: Error deserializing server response
       at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:144)
       at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:89)
       at com.cloudant.mazha.CouchClient.execute(CouchClient.java:193)
       at com.cloudant.mazha.CouchClient.isBulkSupported(CouchClient.java:749)
       at com.cloudant.sync.replication.CouchClientWrapper.isBulkSupported(CouchClientWrapper.java:280)
       at com.cloudant.sync.replication.PullStrategy.run(PullStrategy.java:176)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.net.ConnectException: Connection timed out
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
       at java.net.Socket.connect(Socket.java:586)
       at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
       at com.android.okhttp.Connection.connectSocket(Connection.java:1455)
       at com.android.okhttp.Connection.connect(Connection.java:1413)
       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1707)
       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:133)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:503)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:247)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
       at com.cloudant.http.HttpConnection.responseAsInputStream(HttpConnection.java:420)
       at com.cloudant.mazha.CouchClient.execute(CouchClient.java:176)
       at com.cloudant.mazha.CouchClient.isBulkSupported(CouchClient.java:749)
       at com.cloudant.sync.replication.CouchClientWrapper.isBulkSupported(CouchClientWrapper.java:280)
       at com.cloudant.sync.replication.PullStrategy.run(PullStrategy.java:176)
       at java.lang.Thread.run(Thread.java:762)

#0. Crashed: Replicator: PullStrategy - https://user.cloudant.com:443/topics: 0 0 0x0000000000000000
       at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:144)
       at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:89)
       at com.cloudant.mazha.CouchClient.execute(CouchClient.java:193)
       at com.cloudant.mazha.CouchClient.isBulkSupported(CouchClient.java:749)
       at com.cloudant.sync.replication.CouchClientWrapper.isBulkSupported(CouchClientWrapper.java:280)
       at com.cloudant.sync.replication.PullStrategy.run(PullStrategy.java:176)
       at java.lang.Thread.run(Thread.java:762)
``` 

The error seems to happen on many android versions (4, 5, 6, 7)

I am using cloudant library version `1.1.4`
Thank you.

**Comment by ricellis** [comment] 2017-04-18 08:47
As you can see the problem is that the connection has timed out. There can a number of reasons for this and it isn't possible to identify the cause from this information. Regardless the `Replicator` will error as a result of the connection timeout, posting a `ReplicationErrored` event to the `EventBus` (or in the case of replication policies by a callback of `replicationErrored` on a registered `ReplicationCompleteListener`).
The application should use the error notification to take appropriate action, for example, possibly re-starting the replication.

It is worth noting that the sync-android library typically retries most failed networking requests up to 10 times. The `isBulkSupported` check in the stack trace here was one request that was not integrated with the retry logic until last week (when #479 was resolved by #525 merging) and a release has not been made with that update yet. With that change present the next release will probably reduce the frequency of this specific error by initiating a retry for failures of this particular network request, assuming that the root cause of the connection timeout is not permanent.

Nonetheless an application should still handle the case of `ReplicationErrored` because it is possible that all attempts to retry a network request could fail.

**Closed** 2017-07-19 14:48 UTC
